import operator

dict_orig = {
        "myworkdayjobs.com 1": {"pattern": r".wd1", "scrap_type": "before_scrap_param", "look_for": "wd1.myworkdayjobs.com"},
        "myworkdayjobs.com 2": {"pattern": r".wd3", "scrap_type": "before_scrap_param", "look_for": "wd3.myworkdayjobs.com"},
        "myworkdayjobs.com 3": {"pattern": r".wd5", "scrap_type": "before_scrap_param", "look_for": "wd5.myworkdayjobs.com"},
        "aaimtrack.com": {"pattern": "Job Listings - ", "scrap_type": "after_title"},
        "ultipro.com 1": {"look_for": "recruiting.ultipro.com"},
        "ultipro.com 2": {"look_for": "recruiting2.ultipro.com"},
        "applicantpool.com": {"pattern": "Job Listings - ", "scrap_type": "after_title"},
        "applicantstack.com": {"scrap_type": "before_scrap_param"},
        "applitrack.com": {"pattern": " - Frontl", "scrap_type": "before_title"},
        "appone.com": {"pattern": " Jobs", "scrap_type": "before_title"},
        "apscareerportal.com": {"scrap_param": "//span[contains(@class,'brand')]//@alt"},
        "atsondemand.com": {"scrap_param": "//div[contains(@class,'logo')]//@alt"},
        "avature.net": {"scrap_type": "before_scrap_param"},
        "bamboohr.com": {},
        "breezy.hr": {"scrap_type": "before_scrap_param"},
        "careerplug.com": {"scrap_type": "before_scrap_param"},
        "catsone.com": {"scrap_type": "before_scrap_param"},
        "civicplushrms.com": {"scrap_type": "before_scrap_param"},
        "csod.com": {"scrap_type": "before_scrap_param"},
        "e3applicants.com": {"scrap_param": "//div[contains(@class,'Company')]//a/@title"},
        "easyapply.co": {"pattern": "View jobs at ", "scrap_type": "after_title"},
        "force.com": {"scrap_type": "after_scrap_param"},
        "greenhouse.io": {"pattern": "boards.greenhouse.io/", "scrap_type": "after_scrap_param"},
        "hcshiring.com": {"scrap_param": "//p[@id='clientName']/text()", "look_for": "healthcaresource.com"},
        "hirebridge.com": {"pattern": " Career Center", "look_for": "recruit.hirebridge.com", "scrap_type": "before_title"},
        "hirecentric.com": {"pattern": " Login| Jobs", "scrap_type": "before_title"},
        "hireclick.com": {"pattern": "areer with ", "scrap_type": "after_title"},
        "oraclecloud.com": {"pattern": " Careers", "scrap_type": "before_title", "exclude_str": "Search Jobs - "},
        "selectminds.com": {"pattern": " - Jobs", "scrap_type": "before_title"},
        "smartrecruiters.com": {"look_for": "careers.smartrecruiters.com", "pattern": "careers.smartrecruiters.com/", "scrap_type": "after_scrap_param"},
        "taleo.net": {"scrap_type": "before_scrap_param"},
        "zohorecruit.com": {"scrap_type": "before_scrap_param"},

        'acquiretm.com': {},
        'adp.com': {},
        'applicantpro.com': {"pattern": "Job Listings - ", "scrap_type": "after_title"},
        'apploi.com': {},
        'applytojob.com': {"pattern": " - Career Page", "scrap_type": "before_title"},
        'applytracking.com': {},
        'balancetrak.com': {},
        'brassring.com': {},
        'brt.mv': {},
        'bullhornstaffing.com': {},
        'cadienttalent.com': {},
        'candidatecare.jobs': {"scrap_type": "after_scrap_param"},
        'crelate.com': {},
        'dayforcehcm.com': {},
        'ejob.bz': {"pattern": " Jobs", "scrap_type": "before_title"},
        'entertimeonline.com': {},
        'governmentjobs.com': {},
        'harri.com': {},
        'healthcaresource.com': {},
        'hiremojo.com': {},
        'hireology.com': {},
        'hiretouch.com': {},
        'hodes.com': {},
        'hralliance.net': {},
        'hrapply.com': {},
        'hrdepartment.com': {},
        'hrmdirect.com': {},
        'hrsmart.com': {},
        'icims.com': {},
        'inforcloudsuite.com': {},
        'interfolio.com': {},
        'interviewexchange.com': {},
        'isolvedhire.com': {},
        'jobaline.com': {},
        'jobappnetwork.com': {},
        'jobdiva.com': {},
        'joblinkapply.com': {},
        'jobs.net': {},
        'jobscore.com': {},
        'jobvite.com': {},
        'jsco.re': {},
        'lever.co': {},
        'mykronos.com': {},
        'ourcareerpages.com': {},
        'pageuppeople.com': {},
        'paychex.com': {},
        'paycomdfw.net': {},
        'paycomonline.net': {},
        'paylocity.com': {},
        'peopleadmin.com': {},
        'peopleclick.com': {},
        'peoplefluent.com': {},
        'peoplematter.com': {},
        'recruiterbox.com': {},
        'recruitics.com': {},
        'recruitingbypaycor.com': {},
        'recruitingsite.com': {},
        'recruitpro.com': {},
        'recsolu.com': {},
        'saashr.com': {},
        'schooljobs.com': {},
        'silkroad.com': {},
        'smartsearchonline.com': {},
        'submit4jobs.com': {},
        'successfactors.com': {},
        'successfactors.eu': {},
        'talentplushire.com': {},
        'tedk12.com': {},
        'theapplicantmanager.com': {},
        'theresumator.com': {},
        'trinethire.com': {},
        'ttcportals.com': {},
        'usajobs.gov': {},
        'vikus.net': {},
        'workable.com': {},
        'workbrightats.com': {},
        'zoho.com': {}
            }


sorted = sorted(dict_orig.items())
dict_sorted = {n[0]: n[1] for n in sorted}
print(dict_sorted)

# for name in enumerate(dict_sort):
#     print(name[1][0], 'has spend', dict_orig[name[1][0]])
